"use client";

import { useQuery } from "@tanstack/react-query";
import { api, queryKeys } from "@/lib/ats/api";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Sparkles, RefreshCw, AlertTriangle, Lightbulb, ListChecks } from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { relativeTime } from "@/lib/ats/format";

export function AIBriefCard() {
  const { data, isLoading, isError, refetch, isFetching } = useQuery({
    queryKey: queryKeys.brief,
    queryFn: api.getBrief,
    staleTime: 60 * 1000,
  });

  return (
    <Card className="overflow-hidden border-amber-200 bg-gradient-to-br from-amber-50/80 to-emerald-50/40 dark:border-amber-900/50 dark:from-amber-950/20 dark:to-emerald-950/10">
      <CardHeader className="flex flex-row items-start justify-between gap-2 space-y-0 pb-3">
        <div>
          <CardTitle className="flex items-center gap-2 text-base">
            <Sparkles className="h-4 w-4 text-amber-600 dark:text-amber-400" aria-hidden />
            AI Daily Brief
          </CardTitle>
          <CardDescription className="mt-1 text-xs">
            Generated by zero-token AI · {data ? relativeTime(data.generatedAt) : "loading…"}
          </CardDescription>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={() => {
            refetch();
            toast.success("Regenerating AI brief…");
          }}
          disabled={isFetching}
          aria-label="Regenerate AI brief"
        >
          <RefreshCw className={cn("mr-1.5 h-3.5 w-3.5", isFetching && "animate-spin")} aria-hidden />
          Regenerate
        </Button>
      </CardHeader>
      <CardContent className="space-y-4">
        {isLoading && (
          <div className="space-y-2">
            {[...Array(3)].map((_, i) => (
              <Skeleton key={i} className="h-12 w-full" />
            ))}
          </div>
        )}
        {isError && (
          <div className="flex items-center gap-2 rounded-md bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-950/40 dark:text-rose-300">
            <AlertTriangle className="h-4 w-4" aria-hidden />
            Failed to load AI brief. Try regenerating.
          </div>
        )}
        {data && (
          <>
            <div className="grid gap-2 sm:grid-cols-3">
              {data.priorities.map((p, i) => (
                <div
                  key={i}
                  className={cn(
                    "rounded-lg border bg-background/70 p-3",
                    p.severity === "high" && "border-rose-200 dark:border-rose-900/50",
                    p.severity === "medium" && "border-amber-200 dark:border-amber-900/50",
                    p.severity === "low" && "border-emerald-200 dark:border-emerald-900/50",
                  )}
                >
                  <div className="mb-1 flex items-center gap-1.5">
                    <ListChecks
                      className={cn(
                        "h-3.5 w-3.5",
                        p.severity === "high" && "text-rose-600",
                        p.severity === "medium" && "text-amber-600",
                        p.severity === "low" && "text-emerald-600",
                      )}
                      aria-hidden
                    />
                    <span className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
                      {p.severity} priority
                    </span>
                  </div>
                  <p className="text-sm font-semibold leading-tight">{p.title}</p>
                  <p className="mt-1 text-xs text-muted-foreground">{p.detail}</p>
                </div>
              ))}
            </div>

            {data.needsAttention.length > 0 && (
              <div>
                <p className="mb-2 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                  <Lightbulb className="h-3.5 w-3.5 text-amber-600" aria-hidden />
                  Candidates needing attention
                </p>
                <div className="flex flex-wrap gap-1.5">
                  {data.needsAttention.map((c, i) => (
                    <span
                      key={i}
                      className="inline-flex items-center gap-1.5 rounded-full bg-background px-2.5 py-1 text-xs"
                    >
                      <span className="font-medium">{c.name}</span>
                      <span className="text-muted-foreground">·</span>
                      <span className="text-muted-foreground">{c.reason}</span>
                      <span className="rounded-full bg-emerald-100 px-1.5 text-[10px] font-semibold text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">
                        {c.score}
                      </span>
                    </span>
                  ))}
                </div>
              </div>
            )}

            {data.automationSummary && (
              <div className="rounded-md bg-background/70 p-3 text-xs text-muted-foreground">
                <span className="font-semibold text-foreground">Automation summary:</span>{" "}
                {data.automationSummary}
              </div>
            )}
          </>
        )}
      </CardContent>
    </Card>
  );
}
